version: "3.5"
services:
  webapp-template-frontend:
    build: .
    image: "webapp-template-frontend"
    container_name: "webapp-template-frontend"
    restart: "always"
    networks:
      - "net"
    environment:
      VIRTUAL_HOST: "YOUR_HOST_NAME"
      LETSENCRYPT_HOST: "YOUR_HOST_NAME"
      VIRTUAL_PORT: "80"
networks:
  net:
    external: true